### ISSUE TITLE
Error writing '/EMPTY'

### ISSUE THREAD

**Issue by derek-adair** [torchbox/vagrant-django-base#5]
==> default:  https://registry.npmjs.org/image-size/-/image-size-0.3.5.tgz
==> default: /usr/local/bin/lessc -> /usr/local/lib/node_modules/less/bin/lessc
==> default: less@2.4.0 /usr/local/lib/node_modules/less
==> default: └── image-size@0.3.5
==> default: Zeroing free space to improve compression.
==> default: dd: 
==> default: error writing ‘/EMPTY’
==> default: : No space left on device
==> default: 39012+0 records in
==> default: 39011+0 records out
==> default: 40906375168 bytes (41 GB) copied
==> default: , 44.9171 s, 911 MB/s

[12b91b9ec86865bf4a3bfdbfac6c1b0625face1a](https://github.com/torchbox/vagrant-django-base/commit/12b91b9ec86865bf4a3bfdbfac6c1b0625face1a)  is the offending commit it seems

**Comment by gasman** [comment]
This is the expected behaviour (assuming that it then goes on to create the final VM image). We zero out the free space by creating a file that takes up the entire disk - this process is complete when the command exits with the "No space left on device" error.
