### ISSUE TITLE
lessc not working on initial installation

### ISSUE THREAD

**Issue by se1exin** [torchbox/vagrant-django-base#6]
The default install of lessc on this box produces absolutely no output when running via terminal or when run through django compressor. 

After some Google'in I have been able to successfully correct the problem for each box instance I have created locally using [these instructions](http://askubuntu.com/questions/231090/less-css-compilers-returning-blank) - which essentially just manually removes all node-less binaries and then re-installs node-less via apt-get instead of npm. It would be great if this box was updated to have a working version of lessc pre-installed without the need to do this for every box launched.

Note that I use this box in conjunction with TorchBox's [vagrant-django-template](https://github.com/torchbox/vagrant-django-template) repo - so I am not 100% sure if the source of the issue lies with the box or the provisioning script in the template repo.

**Comment by kaedroho** [comment]
Yep, it looks like we're installing node v0.10.0 which is ancient. Thanks!

I'll update the box.

**Comment by kaedroho** [comment]
Could you check that the box in the "rewrite" branch works for you?

 https://github.com/torchbox/vagrant-django-base/pull/7

**Comment by se1exin** [comment]
The initial box build worked fine along with lessc successfully compiling css, however when used in conjunction with vagrant-django-template I received 2 lots of errors, the first halfway through provisioning, being about postgres:

> ==> default: createdb: could not connect to database template1: FATAL:  Peer authentication failed for user "postgres"

The second was the very last part of provisioning which junked the virtualenv - see [this gist](https://gist.github.com/se1exin/15cc4666f539c0c6d549) for the full error list.

**Comment by se1exin** [comment]
Additionally, when connecting to the box via vagrant ssh, [these errors also occurred](https://gist.github.com/se1exin/af821296b3535fdbcc85)

**Comment by kaedroho** [comment]
Thanks, I rebuilt this box on the wagtail base box which has some recent changes that appear to be incompatible with the old template. I'll update that too in a bit.

In the mean time, that particular error can be solved by removing the -Upostgres part of all postgresql comments. And also removing the 'USER' setting from the database configuration.

**Comment by se1exin** [comment]
Closing to clean up old still-open issues
